#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ; export PATH
cd /usr/share/apache-ofbiz
java -Xms256m -Xmx512m -XX:MaxPermSize=192m -XX:+CMSClassUnloadingEnabled -jar ofbiz.jar

